#152-333	Electrical Engineering Laboratory 3 
#ปฏิบัติการทางวิศวกรรมไฟฟ้า 3

In [ ]:
import numpy as np

Now we can define $A$:

In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [ ]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [ ]:
A.shape

(3, 3)

In [ ]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [ ]:
B.shape

(3, 3)

In [ ]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [ ]:
C = np.array([1,5,7])
C

array([1, 5, 7])

In [ ]:
C.shape

(3,)

In [ ]:
C = np.array([1,5,7]).reshape(3,1)
C

array([[1],
       [5],
       [7]])

In [ ]:
C.shape

(3, 1)

We can obtain the following straightforwardly:

- $5A$ (or any other scalar multiple of $A$);
- $A ^ 3$ (or any other exponent of $A$);
- $A + B$;
- $A - B$;
- $AB$
- $AC$
- $B+AC$

In [ ]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [ ]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [ ]:
A*A*A

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [ ]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [ ]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [ ]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

In [ ]:
A.dot(B)

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

In [ ]:
A*C

matrix([[ 49],
        [172],
        [ 99]])

In [ ]:
(A*C).shape

(3, 1)

In [ ]:
B+A*C

matrix([[ 63,  47,  61],
        [176, 176, 177],
        [104, 104, 100]])

### Transpose

>The transpose of a matrix is another operation that can be accomplished with `numpy`. Its importance isn't so obvious as first, but they're used to <HERE>. Now, let's take a look at an example. Given the matrix below, let's find what its transpose looks like. 

In [ ]:
A.transpose()

matrix([[ 5,  4,  0],
        [ 6,  7,  3],
        [ 2, 19, 12]])

In [ ]:
np.transpose(A)

matrix([[ 5,  4,  0],
        [ 6,  7,  3],
        [ 2, 19, 12]])

### Identity Matrix

A Diagonal Matrix is an n x n matrix with 1s on the diagonal from the top left to the bottom right, such as 

``` 
[[ 1., 0., 0.],
[ 0., 1., 0.],
[ 0., 0., 1.]]
```

We can generate diagonal matrices with the `eye()` function in Python: 


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

**EXERCISE** Compute $A ^ 2 - 2 A + 3$ with:

$$A = 
\begin{pmatrix}
1 & -1\\
2 & 1
\end{pmatrix}
$$
---

In [ ]:
A = np.array([ [1,-1],[2,1] ])
A

array([[ 1, -1],
       [ 2,  1]])

In [ ]:
A**2-2*A+3

array([[2, 6],
       [3, 2]])

---

**EXERCISE** Compute the solutions to the matrix equation $Bx=b$ (using the $B$ defined earlier).

---

## Matrix inversion and determinants

>Computing the inverse of a matrix is straightforward:

We can verify that $A^{-1}A=\mathbb{1}$:

In [ ]:
A * Ainv

matrix([[  1.00000000e+00,   2.77555756e-17,   3.05311332e-16],
        [ -2.08166817e-16,   1.00000000e+00,  -2.08166817e-16],
        [  5.55111512e-17,  -5.55111512e-17,   1.00000000e+00]])

In [ ]:
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.20930233,  0.51162791, -0.7751938 ],
        [ 0.37209302, -0.46511628,  0.6744186 ],
        [-0.09302326,  0.11627907, -0.08527132]])

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).


---

## Solving Matrix equations

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$

Let us illustrate that with:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-1\\
2\\
1 
\end{pmatrix}
$$

$$x=A^{-1}b $$



In [ ]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command:

In [ ]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

In [ ]:
 x= np.linalg.inv(A)*b
 x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

We can verify our result:

In [ ]:
A * x

matrix([[-1.],
        [ 2.],
        [ 1.]])

#To calculate the determinant:

In [ ]:
np.linalg.det(A)

-129.00000000000009

### What is a Norm? 

The actual formula looks like: 

$$ ||v|| = \sqrt{v_1^2 + ... + v_n^2} $$

In [ ]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [ ]:
np.linalg.norm(v)

5.477225575051661

#ตัวอย่าง 1
#จงแก้สมการต่อไปนี้

#$\displaylines{
   - 9x - 12y + 15z =  - 14 \cr 
  2x - 7y =  - 3 - {1 \over 5}z \cr 
   - 2y + z =  - 8 + 5x \cr} $

</br>
วิธีทำจัดรูปใหม่
</br>

#$\displaylines{
   - 9x - 12y + 15z =  - 14 \cr 
  2x - 7y + {1 \over 5}z =  - 3 \cr 
   - 5x - 2y + z =  - 8 \cr} $



   $$
A = \begin{pmatrix}
-9 & -12 & 15\\
2 & -7 & 1/5\\
-5 & -2 & 1
\end{pmatrix}
$$

$$
b = \begin{pmatrix}
-14\\
-3\\
-8 
\end{pmatrix}
$$

$$Ax=b$$

$$x=A^{-1}b $$


In [ ]:
A = np.matrix([ [-9 ,-12 , 15] ,[2 ,-7  ,1/5], [-5,-2,1] ] )
b = np.matrix( [[-14],[-3],[8]])



In [ ]:
A

matrix([[ -9. , -12. ,  15. ],
        [  2. ,  -7. ,   0.2],
        [ -5. ,  -2. ,   1. ]])

In [ ]:
A.shape

(3, 3)

In [ ]:
b

array([[-14],
       [ -3],
       [  8]])

In [ ]:
b.shape

(3, 1)

In [ ]:
x = np.linalg.solve(A, b)
x

matrix([[-1.9754902 ],
        [-0.20098039],
        [-2.27941176]])

In [ ]:
x= np.linalg.inv(A)*b
x

matrix([[-1.9754902 ],
        [-0.20098039],
        [-2.27941176]])

#ตัวอย่าง 2

จงหาค่า $i_1$ และ $i_2$

![rrfffdwde](https://github.com/Tuchsanai/152-333-/blob/master/images/2020-07-09_15-20-44.png?raw=true)


#$\begin{array}{c}
\left( {20 + 20} \right){i_1} - 20{i_2} = 40\\
 - 20{i_1} - \left( {40 + 20} \right) = 0
\end{array}$

#จัดรูปใหม่

#$\begin{array}{c}
40{i_1} - 20{i_2} = 40\\
 - 20{i_1} - 60 i_2 = 0
\end{array}$

In [ ]:
A = np.matrix([ [40,-20 ] ,[-20 ,-60  ] ] )
b = np.matrix( [[40],[0]])

In [ ]:
A

matrix([[ 40, -20],
        [-20, -60]])

In [ ]:
b

matrix([[40],
        [ 0]])

In [ ]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.85714286],
        [-0.28571429]])

#แบบฝึกหัด 

จงหาค่า $i_1$  $i_2$   $i_3$

![frfr](https://github.com/Tuchsanai/152-333-/blob/master/images/2020-07-09_15-48-34.png?raw=true)