#152-333	Electrical Engineering Laboratory 3 
#ปฏิบัติการทางวิศวกรรมไฟฟ้า 3

[*ศึกษาเพิ่ม*](https://www.youtube.com/watch?v=fI9Q_haTnVI&t=87s)

<iframe width="420" height="315"
src="https://www.youtube.com/watch?v=fI9Q_haTnVI&t=87s">
</iframe>


In [ ]:
import numpy as np

#Basic polynomial functions  example


ตัวอย่างของ polynomial 
- $p(s)=a_n s^n + a_{n-1}s^{n-1} + \dotsb + a_2 s^2 + a_1 s + a_0$
- $p(s)=(s-p_{1})(s-p_{2})(s-p_{3}) \dotsb (s-p_{n})$





## ตัวอย่าง : จงสร้าง polynomial functions  จากเงือนไข


# $p(s)=(s-1)(s-3)(s-5)$


In [ ]:
np.poly([1,3,5])

array([  1.,  -9.,  23., -15.])

# ตัวอย่าง จงหาราก (roots) ของ  
# $p(s)= s^3  -9s^{2} +23s-15$

In [ ]:
np.roots([1,-9,23,-15])

array([5., 3., 1.])

#ตัวอย่างการคูณ Polynomial

# $r(s) = (s^3  -9s^{2} +23s-15)(s^2  - 1)$


In [ ]:
np.polymul([1, -9,  23, -15], [1, 0, -1])

array([  1,  -9,  22,  -6, -23,  15])

#ตัวอย่างการคูณ Polynomial

#$r(s) = (s^3  -9s^{2} +23s-15)(s-1)(s-3)(s-5)$


In [ ]:
np.polymul([1, -9,  23, -15], np.poly([1,3,5]))

array([   1.,  -18.,  127., -444.,  799., -690.,  225.])

# ตัวอย่าง จงหาราก (roots) ของ  
#$r(s) = (s^3  -9s^{2} +23s-15)(s-4)(s-8)(s+9)$

In [ ]:
r = np.polymul([1, -9,  23, -15], np.poly([4,8,-9]))
r

array([ 1.000e+00, -1.200e+01, -2.600e+01,  8.880e+02, -4.295e+03,
        7.764e+03, -4.320e+03])

In [ ]:
np.roots(r)

array([-9.,  8.,  5.,  4.,  3.,  1.])