<a href="https://colab.research.google.com/github/Tuchsanai/152-333-Electrical-Engineering-Laboratory-3/blob/master/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [47]:
X = np.random.randint(0,10,(100,2))

In [51]:
X[0:10]

array([[1, 4],
       [6, 2],
       [4, 8],
       [4, 5],
       [6, 9],
       [0, 2],
       [6, 8],
       [9, 5],
       [2, 2],
       [6, 9]])

In [52]:
model =  NearestNeighbors(n_neighbors=3)
model.fit(X)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                 radius=1.0)

In [53]:
distance,index = model.kneighbors(X)

In [59]:
idx= np.where( distance[:,1:] ==0)[0]
idx

array([ 0,  2,  3,  4,  5,  9, 11, 12, 13, 13, 14, 14, 15, 16, 17, 19, 20,
       21, 21, 22, 22, 23, 23, 25, 27, 29, 31, 31, 33, 34, 35, 35, 37, 37,
       39, 41, 43, 44, 45, 45, 47, 49, 49, 50, 50, 51, 53, 53, 54, 55, 55,
       56, 57, 58, 59, 59, 61, 61, 62, 62, 63, 63, 64, 64, 65, 65, 67, 68,
       68, 71, 71, 73, 75, 77, 78, 78, 79, 79, 80, 81, 82, 83, 83, 84, 84,
       86, 86, 88, 89, 90, 91, 94, 97, 98, 98, 99])

In [60]:
distance[idx]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0

In [46]:
index[idx]

array([[ 0, 11, 52],
       [ 1, 12, 14],
       [ 1, 12, 14],
       [18,  2, 99],
       [18,  2, 99],
       [ 3, 24, 61],
       [63,  4, 54],
       [63,  4, 54],
       [63,  4, 54],
       [ 5, 50,  4],
       [80, 14,  6],
       [80, 14,  6],
       [80, 14,  6],
       [43, 98,  7],
       [43, 98,  7],
       [43, 98,  7],
       [ 8, 83, 21],
       [ 8, 83, 21],
       [ 9, 81, 22],
       [44, 10, 26],
       [44, 10, 26],
       [11, 65,  0],
       [11, 65,  0],
       [ 1, 12, 14],
       [ 1, 12, 14],
       [91, 13, 75],
       [91, 13, 75],
       [80, 14,  6],
       [80, 14,  6],
       [80, 14,  6],
       [15, 87, 59],
       [15, 87, 59],
       [16, 33, 20],
       [16, 33, 20],
       [60, 17, 48],
       [60, 17, 48],
       [60, 17, 48],
       [18,  2, 99],
       [18,  2, 99],
       [46, 19, 73],
       [46, 19, 73],
       [20, 33, 16],
       [21, 52,  0],
       [22,  9, 76],
       [23, 73, 37],
       [23, 73, 37],
       [24,  3, 41],
       [25, 7

In [64]:
for ix in index[idx] :
  print('x0 = ', X[ix[0]] , 'x1 = ',X[ix[1]], 'x2 = ',X[ix[2]] )

x0 =  [1 4] x1 =  [1 4] x2 =  [1 5]
x0 =  [4 8] x1 =  [4 8] x2 =  [3 8]
x0 =  [4 5] x1 =  [4 5] x2 =  [3 5]
x0 =  [6 9] x1 =  [6 9] x2 =  [6 8]
x0 =  [0 2] x1 =  [0 2] x2 =  [0 1]
x0 =  [6 9] x1 =  [6 9] x2 =  [6 8]
x0 =  [4 4] x1 =  [4 4] x2 =  [4 5]
x0 =  [6 7] x1 =  [6 7] x2 =  [5 7]
x0 =  [0 1] x1 =  [0 1] x2 =  [0 1]
x0 =  [0 1] x1 =  [0 1] x2 =  [0 1]
x0 =  [4 7] x1 =  [4 7] x2 =  [4 7]
x0 =  [4 7] x1 =  [4 7] x2 =  [4 7]
x0 =  [0 2] x1 =  [0 2] x2 =  [0 1]
x0 =  [0 6] x1 =  [0 6] x2 =  [0 7]
x0 =  [5 4] x1 =  [5 4] x2 =  [4 4]
x0 =  [6 4] x1 =  [6 4] x2 =  [5 4]
x0 =  [3 5] x1 =  [3 5] x2 =  [3 6]
x0 =  [1 5] x1 =  [1 5] x2 =  [1 5]
x0 =  [1 5] x1 =  [1 5] x2 =  [1 5]
x0 =  [0 1] x1 =  [0 1] x2 =  [0 1]
x0 =  [0 1] x1 =  [0 1] x2 =  [0 1]
x0 =  [9 3] x1 =  [9 3] x2 =  [9 3]
x0 =  [9 3] x1 =  [9 3] x2 =  [9 3]
x0 =  [6 3] x1 =  [6 3] x2 =  [6 4]
x0 =  [4 8] x1 =  [4 8] x2 =  [3 8]
x0 =  [4 0] x1 =  [4 0] x2 =  [3 0]
x0 =  [4 6] x1 =  [4 6] x2 =  [4 6]
x0 =  [4 6] x1 =  [4 6] x2 =